#!/bin/bash

echo "====================================================================";
echo " Test1: Use -1, -2 options to assign reads files"
echo "====================================================================";
rm -rf testout1
rm -rf reads_data
mkdir -p testout1
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -1 input/reads1_200.fq -2 input/reads2_200.fq -R ./reads_data -z 200 -s arabidopsis -t protein -x 15000 -n 10 -P Params.conf -o testout1
echo "====================================================================";
echo " Test2: Use library definition file (-f) and -R option. The previous preprocessed data is used"
echo "====================================================================";
rm -rf testout2
mkdir -p testout2
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                            -R ./reads_data -s arabidopsis -t protein -x 15000 -n 10 -P Params.conf -o testout2
echo "====================================================================";
echo " Test3: Use two libraries. Only 2nd library will be preprocessed"
echo "====================================================================";
rm -rf testout3
mkdir -p testout3
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -o testout3
echo "====================================================================";
echo " Test4: Use two libraries with MPI feature"
echo "====================================================================";
rm -rf testout4
mkdir -p testout4
mpirun -n 4 ../bin/SRAssembler_MPI -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -o testout4
