#!/bin/bash

echo "====================================================================";
echo " Test1: Use -1, -2 options to assign reads files"
echo "====================================================================";
rm -rf testout1
rm -rf reads_data
mkdir -p testout1
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -1 input/reads1_200.fq -2 input/reads2_200.fq -R ./reads_data -z 200 -s arabidopsis -t protein -x 15000 -n 10 -P Params.conf -o testout1
echo "====================================================================";
echo " Test2: Use library definition file (-f) and -R option. The previous preprocessed data is used"
echo "====================================================================";
rm -rf testout2
mkdir -p testout2
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                            -R ./reads_data -s arabidopsis -t protein -x 15000 -n 10 -P Params.conf -o testout2
echo "====================================================================";
echo " Test3: Use two libraries. Only 2nd library will be preprocessed"
echo "====================================================================";
rm -rf testout3
mkdir -p testout3
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -o testout3
echo "====================================================================";
echo " Test4: Use two libraries with MPI feature"
echo "====================================================================";
rm -rf testout4
mkdir -p testout4
mpirun -n 4 ../bin/SRAssembler_MPI -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -o testout4
echo "====================================================================";
echo " Test5.1: Test 3 rounds. Then the second test continue previous assembling."
echo "====================================================================";
rm -rf testout5
mkdir -p testout5
../bin/SRAssembler -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -G 1 -P Params.conf -o testout5
echo " Now rerun previous run, but set -n to 7. The assembling starts at 4th round"
echo "====================================================================";
../bin/SRAssembler -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  7 -G 1 -P Params.conf -o testout5
echo "====================================================================";
echo " Test5.2: Rerun previous run, but use -i to force SRAssembler to start from scratch"
echo "====================================================================";
../bin/SRAssembler -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  7 -i -G 1 -P Params.conf -o testout5
echo "====================================================================";
echo " Test6: Use higher score (-e 0.6) and coverage (-c 0.9)"
echo "====================================================================";
rm -rf testout6
mkdir -p testout6
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  10 -c 0.9 -e 0.6 -P Params.conf -o testout6
echo "====================================================================";
echo " Test7: Use GeneSeqer as spliced alignment program (-S 1)"
echo "====================================================================";
rm -rf testout7
mkdir -p testout7
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -S 1 -P Params.conf -o testout7
echo "====================================================================";
echo " Test8: Use Exonerate as spliced alignment program (-S 2)"
echo "====================================================================";
rm -rf testout8
mkdir -p testout8
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -S 2 -c 2000 -e 1000 -P Params.conf -o testout8
echo "====================================================================";
echo " Test9: Use Snap as ab initio gene prediction program (-G 1)"
echo "====================================================================";
rm -rf testout9
mkdir -p testout9
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -G 1 -P Params.conf -o testout9
echo "====================================================================";
echo " Test10: Do preprocessing only (-p)"
echo "====================================================================";
rm -rf testout10
mkdir -p testout10
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp_1kb.config                        -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -o testout10 -p
echo "====================================================================";
echo " Test11: Remove unrelated contigs and reads every 2 rounds (-r 2)"
echo "====================================================================";
rm -rf testout11
mkdir -p testout11
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -r 2 -P Params.conf -o testout11
echo "====================================================================";
echo " Test12: Assemble contigs from 2nd round (-a 2)"
echo "====================================================================";
rm -rf testout12
mkdir -p testout12
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -a 2 -P Params.conf -o testout12
echo "====================================================================";
echo " Test13: Do not check if the query genes are assembled (-l)"
echo "====================================================================";
rm -rf testout13
mkdir -p testout13
../bin/SRAssembler     -q input/LOC_Os06g04560.pep -f libraries_200bp.config                        -R ./reads_data -s arabidopsis -t protein -x 15000 -n  3 -P Params.conf -l -o testout13
